# Site settings
title: HEcPanel
email: support@dynamictivity.com
url: https://dynamictivity.github.io/hecpanel
description: "HEcPanel (Hosted Engineers Control Panel)  The ultimate hosting solution for Keen software's titles: Space Engineers, and Medieval Engineers"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Dynamictivity

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hecpanel
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/hecpanel
  - title: bitbucket
    url: http://bitbucket.org/dynamictivity
  - title: github
    url: https://github.com/dynamictivity/hecpanel

# Build settings
markdown: kramdown
permalink: pretty
